# Generated by Django 5.0.6 on 2024-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleyeeTbl',
            fields=[
                ('emp_number', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_role', models.CharField(choices=[('Manager', 'Manager'), ('Intern', 'Intern'), ('Jr Developer', 'Jr Developer'), ('Sr Developer', 'Sr Developer'), ('Analyst', 'Analyst'), ('HR', 'HR')], max_length=50)),
            ],
        ),
    ]
