# Generated by Django 5.0.6 on 2024-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_dynamicform_employee_formfield_formfieldvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicform',
            old_name='name',
            new_name='dynamicform_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='form',
            new_name='dynamicform',
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='form',
            new_name='dynamicform',
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='label',
            new_name='form_field',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('Password', 'Password')], max_length=50),
        ),
    ]
